### ISSUE TITLE
Vulnerable version detected

### ISSUE THREAD

**Issue by Ankireddy85** [HCL-TECH-SOFTWARE/appscan-issue-gateway#44]
Vulnerable version for Jackson-databind, SnakeYAML etc. were detected on installation of v0.3.3 Jar

**Comment by mattmurp** [comment]
This has been fixed in version 1.0.0, which is currently being tested. There is a pre-release available while testing is being performed.

**Comment by mattmurp** [comment]
This was fixed in version 1.0.0.
https://github.com/HCL-TECH-SOFTWARE/appscan-issue-gateway/releases/tag/v1.0.0
